services:
  backend:
    build: 
      context: ./backend
    container_name: yt_clipper_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/output:/app/output
      - ./backend/temp:/app/temp
      - ./backend/clips:/app/clips
      - ./backend/youtube_cookies.txt:/app/youtube_cookies.txt:ro
      - ./backend/credentials:/app/credentials:ro
    environment:
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - RECIPIENT_EMAIL=${RECIPIENT_EMAIL:-numanarif.videos@gmail.com}
      - BASE_URL=${BASE_URL:-http://136.110.35.155:8080}
      - PYANNOTE_AUTH_TOKEN=${PYANNOTE_AUTH_TOKEN}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SPREADSHEET_ID=1LjiJ-LAOXX3MKiarUSAmRS7BKeUlsglSiiBDXU24C-I
      - GOOGLE_CREDENTIALS_PATH=${GOOGLE_CREDENTIALS_PATH:-credentials/google_sheets_credentials.json}
      - CRON_INTERVAL_MINUTES=${CRON_INTERVAL_MINUTES:-15}
      - GOOGLE_DRIVE_FOLDER_ID=${GOOGLE_DRIVE_FOLDER_ID}
      - GOOGLE_DRIVE_TOKEN_PATH=${GOOGLE_DRIVE_TOKEN_PATH:-credentials/google_drive_token.json}
    restart: always

  frontend:
    build: 
      context: ./frontend
    container_name: yt_clipper_frontend
    ports:
      - "8080:8080"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: always
